# Generated by Django 2.0.5 on 2018-05-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('store', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
